# Generated by Django 4.1.1 on 2022-10-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='assignments/images')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassesData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='edtech.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='edtech.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='edtech.student')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(auto_now=True)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edtech.batch')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edtech.image')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edtech.student')),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=300)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('image', models.ImageField(default='', upload_to='assignments/images')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='edtech.batch')),
            ],
        ),
    ]
