# Generated by Django 4.1.1 on 2022-10-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0003_alter_batch_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
