# Generated by Django 4.1.1 on 2022-10-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0006_alter_classesdata_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classesdata',
            old_name='batch_id',
            new_name='batch',
        ),
    ]
