# Generated by Django 4.1.1 on 2022-10-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0007_rename_batch_id_classesdata_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignments',
            options={'verbose_name_plural': 'Assignments'},
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='image_id',
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='assignmentSubmissionImages/images')),
                ('AssignmentSubmission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='edtech.assignmentsubmission')),
            ],
        ),
    ]
