# Generated by Django 4.1.1 on 2022-10-27 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0008_alter_assignments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='Assignments',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='edtech.assignments'),
            preserve_default=False,
        ),
    ]
