# Generated by Django 4.1.1 on 2022-10-27 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0010_rename_batch_id_assignmentsubmission_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmissionimage',
            name='image',
            field=models.ImageField(default='', upload_to='assignments/images'),
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='edtech.batch')),
            ],
        ),
    ]
