# Generated by Django 4.1.1 on 2022-10-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0011_alter_assignmentsubmissionimage_image_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('Filedata', models.FileField(default='', upload_to='StudyMaterial/Files')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edtech.batch')),
            ],
        ),
    ]
