# Generated by Django 4.1.1 on 2022-10-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0012_studymaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='Filedata',
            new_name='fileData',
        ),
    ]
