# Generated by Django 4.1.1 on 2022-11-01 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0013_rename_filedata_studymaterial_filedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='student',
            field=models.ManyToManyField(to='edtech.student'),
        ),
        migrations.CreateModel(
            name='SignUpStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='edtech.student')),
            ],
        ),
    ]
