# Generated by Django 4.1.1 on 2022-11-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0014_batch_student_signupstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupstudent',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='signupstudent',
            name='username',
        ),
    ]
