# Generated by Django 4.1.1 on 2022-11-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0015_remove_signupstudent_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SignUpStudent',
        ),
    ]
