# Generated by Django 4.1.1 on 2022-11-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0017_rename_mobile_student_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='name',
        ),
    ]
