# Generated by Django 4.1.1 on 2022-11-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0018_rename_student_name_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='student',
            field=models.ManyToManyField(related_name='Batches', to='edtech.student'),
        ),
    ]
