# Generated by Django 4.1.1 on 2022-11-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0019_alter_batch_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmissionimage',
            name='image',
            field=models.ImageField(upload_to='assignments/images'),
        ),
    ]
