# Generated by Django 4.1.1 on 2022-11-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edtech', '0022_alter_assignmentsubmissionimage_image_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
